app/kerttu_global/views/permissions.py
from app import db, auth
from flask import Blueprint, render_template, redirect, url_for, request
from app.kerttu_global.models.models import GlobalSite, GlobalSitePermission
from app.services.lajiAPI import get_user_name

global_permissions_page = Blueprint('global_permissions_page', __name__, template_folder='../templates')


@global_permissions_page.route('', methods=['GET'])
@auth.login_required
def permission_form():
    users_by_site = {}
    site_name_map = {}
    user_name_map = {}

    sites = GlobalSite.query.filter(GlobalSite.limit_access == True).all()
    for site in sites:
        users_by_site[site.id] = []
        site_name_map[site.id] = site.name

    permissions = GlobalSitePermission.query.all()
    for p in permissions:
        if p.site_id not in users_by_site:
            users_by_site[p.site_id] = []
            site_name_map[p.site_id] = p.site.name
        users_by_site[p.site_id].append(p.user_id)

    user_ids = list(set([p.user_id for p in permissions]))
    for user_id in user_ids:
        user_name_map[user_id] = get_user_name(user_id)

    return render_template(
        'permissions.html',
        users_by_site=users_by_site,
        site_name_map=site_name_map,
        user_name_map=user_name_map
    )


@global_permissions_page.route('/add', methods=['POST'])
@auth.login_required
def add():
    user_id = request.form['userId']
    site_id = request.form['siteId']

    if get_user_name(user_id) is not None:
        permission = GlobalSitePermission(user_id=user_id, site_id=site_id)
        db.session.add(permission)
        db.session.commit()

    return redirect(url_for('global_permissions_page.permission_form'))


@global_permissions_page.route('/remove', methods=['POST'])
@auth.login_required
def remove():
    user_id = request.form['userId']
    site_id = request.form['siteId']

    GlobalSitePermission.query.filter(
        GlobalSitePermission.user_id == user_id,
        GlobalSitePermission.site_id == site_id
    ).delete()
    db.session.commit()

    return redirect(url_for('global_permissions_page.permission_form'))

app/kerttu_global/views/results.py
from app import app, auth
from flask import Blueprint, request, render_template
from app.kerttu_global.models.models import GlobalContinent, GlobalOrder, GlobalFamily
from app.kerttu_global.services.database.query_service import get_template_results_query
from app.utils.database_utils import query_to_dataframe
from app.utils.view_utils import stream_response
import tempfile
import os

global_results_page = Blueprint('global_results_page', __name__, template_folder='../templates')


@global_results_page.route('', methods=['GET'])
@auth.login_required
def results():
    continents = GlobalContinent.query.order_by(GlobalContinent.id).all()
    orders = GlobalOrder.query.order_by(GlobalOrder.order_order).all()
    families = GlobalFamily.query.order_by(GlobalFamily.family_order).all()

    return render_template('results.html', continents=continents, orders=orders, families=families)


@global_results_page.route('/download', methods=['POST'])
@auth.login_required
def download():
    continent = request.form.get('continent', None, type=int)
    order = request.form.get('order', None, type=int)
    family = request.form.get('family', None, type=int)
    min_validations = request.form.get('minValidations', 0, type=int)

    df = _get_results_df(continent, order, family, min_validations)

    os.makedirs(app.config['TMP_FOLDER'], exist_ok=True)
    tmp_folder = tempfile.mkdtemp(dir=app.config['TMP_FOLDER'])
    file_path = os.path.join(tmp_folder, 'bsg_results.tsv')
    df.to_csv(file_path, sep='\t', index=False)

    return stream_response(file_path, tmp_folder, 'bsg_results.tsv', 'text/tab-separated-value')


def _get_results_df(continent, order, family, min_validations):
    df = query_to_dataframe(get_template_results_query(continent, order, family, min_validations))
    df['file_name'] = df['url'].str.split('/').str[-1]
    return df

app/kerttu_global/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

app/kerttu_global/templates/permissions.html
{% extends "base.html" %}
{% block title %}Bird Sounds Global Permissions{% endblock %}
{% block content %}
<h1>Bird Sounds Global Permissions</h1>
{% for site_id, users in users_by_site.items() %}
<h2>Site {{ site_id }} ({{ site_name_map[site_id] }})</h2>
<lu>
    {% for user_id in users %}
    <li style="padding: 5px 0">
        {{ user_id }} ({{ user_name_map[user_id] }})
        <form action="{{ url_for('global_permissions_page.remove') }}" method="post" style="display: inline-block">
            <input name="siteId" type="hidden" required value="{{ site_id }}">
            <input name="userId" type="hidden" required value="{{ user_id }}">
            <button type="submit">Remove</button>
        </form>
    </li>
    {% endfor %}
</lu>
<form action="{{ url_for('global_permissions_page.add') }}" method="post">
    <input name="siteId" type="hidden" required value="{{ site_id }}">
    <input name="userId" type="text" placeholder="User ID" required>
    <button type="submit">Add</button>
</form>
{% endfor %}
{% endblock %}

app/kerttu_global/templates/results.html
{% extends "base.html" %}
{% block title %}Bird Sounds Global Results{% endblock %}
{% block content %}
<h1>Bird Sounds Global Results</h1>
<form action="{{ url_for('global_results_page.download') }}" method="post">
    <div style="margin: 10px 0">
        <label for="continent">Continent</label>
        <select id="continent" name="continent">
            <option value="" selected></option>
            {% for continent in continents %}
            <option value="{{continent.id}}">{{continent.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div style="margin: 10px 0">
        <label for="order">Order</label>
        <select id="order" name="order">
            <option value="" selected></option>
            {% for order in orders %}
            <option value="{{order.id}}">{{order.scientific_name}}</option>
            {% endfor %}
        </select>
    </div>
    <div style="margin: 10px 0">
        <label for="family">Family</label>
        <select id="family" name="family">
            <option value="" selected></option>
            {% for family in families %}
            <option value="{{family.id}}">{{family.scientific_name}}</option>
            {% endfor %}
        </select>
    </div>
    <div style="margin: 10px 0">
        <label for="minValidations">Minimum number of validations</label>
        <input id="minValidations" name="minValidations" type="number" min="0" value="2">
    </div>

    <button type="submit" value="Submit">Download</button>
</form>
{% endblock %}